# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/sergei/Documents/CPProject — копия 4"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/sergei/Documents/CPProject — копия 4"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/sergei/Documents/CPProject — копия 4/CMakeFiles" "/Users/sergei/Documents/CPProject — копия 4/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/sergei/Documents/CPProject — копия 4/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CPProject.out

# Build rule for target.
CPProject.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CPProject.out
.PHONY : CPProject.out

# fast build rule for target.
CPProject.out/fast:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/build
.PHONY : CPProject.out/fast

#=============================================================================
# Target rules for targets named Google_Tests_run

# Build rule for target.
Google_Tests_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Google_Tests_run
.PHONY : Google_Tests_run

# fast build rule for target.
Google_Tests_run/fast:
	$(MAKE) -f Sources/StaticGeneration/Google_tests/CMakeFiles/Google_Tests_run.dir/build.make Sources/StaticGeneration/Google_tests/CMakeFiles/Google_Tests_run.dir/build
.PHONY : Google_Tests_run/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f Sources/StaticGeneration/Google_tests/googletest/googlemock/CMakeFiles/gmock.dir/build.make Sources/StaticGeneration/Google_tests/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f Sources/StaticGeneration/Google_tests/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make Sources/StaticGeneration/Google_tests/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f Sources/StaticGeneration/Google_tests/googletest/googletest/CMakeFiles/gtest_main.dir/build.make Sources/StaticGeneration/Google_tests/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f Sources/StaticGeneration/Google_tests/googletest/googletest/CMakeFiles/gtest.dir/build.make Sources/StaticGeneration/Google_tests/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Sources/DataBase/Base/BaseComporator.o: Sources/DataBase/Base/BaseComporator.cpp.o

.PHONY : Sources/DataBase/Base/BaseComporator.o

# target to build an object file
Sources/DataBase/Base/BaseComporator.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseComporator.cpp.o
.PHONY : Sources/DataBase/Base/BaseComporator.cpp.o

Sources/DataBase/Base/BaseComporator.i: Sources/DataBase/Base/BaseComporator.cpp.i

.PHONY : Sources/DataBase/Base/BaseComporator.i

# target to preprocess a source file
Sources/DataBase/Base/BaseComporator.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseComporator.cpp.i
.PHONY : Sources/DataBase/Base/BaseComporator.cpp.i

Sources/DataBase/Base/BaseComporator.s: Sources/DataBase/Base/BaseComporator.cpp.s

.PHONY : Sources/DataBase/Base/BaseComporator.s

# target to generate assembly for a file
Sources/DataBase/Base/BaseComporator.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseComporator.cpp.s
.PHONY : Sources/DataBase/Base/BaseComporator.cpp.s

Sources/DataBase/Base/BaseContainer.o: Sources/DataBase/Base/BaseContainer.cpp.o

.PHONY : Sources/DataBase/Base/BaseContainer.o

# target to build an object file
Sources/DataBase/Base/BaseContainer.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseContainer.cpp.o
.PHONY : Sources/DataBase/Base/BaseContainer.cpp.o

Sources/DataBase/Base/BaseContainer.i: Sources/DataBase/Base/BaseContainer.cpp.i

.PHONY : Sources/DataBase/Base/BaseContainer.i

# target to preprocess a source file
Sources/DataBase/Base/BaseContainer.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseContainer.cpp.i
.PHONY : Sources/DataBase/Base/BaseContainer.cpp.i

Sources/DataBase/Base/BaseContainer.s: Sources/DataBase/Base/BaseContainer.cpp.s

.PHONY : Sources/DataBase/Base/BaseContainer.s

# target to generate assembly for a file
Sources/DataBase/Base/BaseContainer.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseContainer.cpp.s
.PHONY : Sources/DataBase/Base/BaseContainer.cpp.s

Sources/DataBase/Base/BaseDataStructure.o: Sources/DataBase/Base/BaseDataStructure.cpp.o

.PHONY : Sources/DataBase/Base/BaseDataStructure.o

# target to build an object file
Sources/DataBase/Base/BaseDataStructure.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseDataStructure.cpp.o
.PHONY : Sources/DataBase/Base/BaseDataStructure.cpp.o

Sources/DataBase/Base/BaseDataStructure.i: Sources/DataBase/Base/BaseDataStructure.cpp.i

.PHONY : Sources/DataBase/Base/BaseDataStructure.i

# target to preprocess a source file
Sources/DataBase/Base/BaseDataStructure.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseDataStructure.cpp.i
.PHONY : Sources/DataBase/Base/BaseDataStructure.cpp.i

Sources/DataBase/Base/BaseDataStructure.s: Sources/DataBase/Base/BaseDataStructure.cpp.s

.PHONY : Sources/DataBase/Base/BaseDataStructure.s

# target to generate assembly for a file
Sources/DataBase/Base/BaseDataStructure.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseDataStructure.cpp.s
.PHONY : Sources/DataBase/Base/BaseDataStructure.cpp.s

Sources/DataBase/Base/BaseMetrificator.o: Sources/DataBase/Base/BaseMetrificator.cpp.o

.PHONY : Sources/DataBase/Base/BaseMetrificator.o

# target to build an object file
Sources/DataBase/Base/BaseMetrificator.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseMetrificator.cpp.o
.PHONY : Sources/DataBase/Base/BaseMetrificator.cpp.o

Sources/DataBase/Base/BaseMetrificator.i: Sources/DataBase/Base/BaseMetrificator.cpp.i

.PHONY : Sources/DataBase/Base/BaseMetrificator.i

# target to preprocess a source file
Sources/DataBase/Base/BaseMetrificator.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseMetrificator.cpp.i
.PHONY : Sources/DataBase/Base/BaseMetrificator.cpp.i

Sources/DataBase/Base/BaseMetrificator.s: Sources/DataBase/Base/BaseMetrificator.cpp.s

.PHONY : Sources/DataBase/Base/BaseMetrificator.s

# target to generate assembly for a file
Sources/DataBase/Base/BaseMetrificator.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseMetrificator.cpp.s
.PHONY : Sources/DataBase/Base/BaseMetrificator.cpp.s

Sources/DataBase/Base/BaseSearchEngine.o: Sources/DataBase/Base/BaseSearchEngine.cpp.o

.PHONY : Sources/DataBase/Base/BaseSearchEngine.o

# target to build an object file
Sources/DataBase/Base/BaseSearchEngine.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseSearchEngine.cpp.o
.PHONY : Sources/DataBase/Base/BaseSearchEngine.cpp.o

Sources/DataBase/Base/BaseSearchEngine.i: Sources/DataBase/Base/BaseSearchEngine.cpp.i

.PHONY : Sources/DataBase/Base/BaseSearchEngine.i

# target to preprocess a source file
Sources/DataBase/Base/BaseSearchEngine.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseSearchEngine.cpp.i
.PHONY : Sources/DataBase/Base/BaseSearchEngine.cpp.i

Sources/DataBase/Base/BaseSearchEngine.s: Sources/DataBase/Base/BaseSearchEngine.cpp.s

.PHONY : Sources/DataBase/Base/BaseSearchEngine.s

# target to generate assembly for a file
Sources/DataBase/Base/BaseSearchEngine.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/Base/BaseSearchEngine.cpp.s
.PHONY : Sources/DataBase/Base/BaseSearchEngine.cpp.s

Sources/DataBase/KD/Container.o: Sources/DataBase/KD/Container.cpp.o

.PHONY : Sources/DataBase/KD/Container.o

# target to build an object file
Sources/DataBase/KD/Container.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/Container.cpp.o
.PHONY : Sources/DataBase/KD/Container.cpp.o

Sources/DataBase/KD/Container.i: Sources/DataBase/KD/Container.cpp.i

.PHONY : Sources/DataBase/KD/Container.i

# target to preprocess a source file
Sources/DataBase/KD/Container.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/Container.cpp.i
.PHONY : Sources/DataBase/KD/Container.cpp.i

Sources/DataBase/KD/Container.s: Sources/DataBase/KD/Container.cpp.s

.PHONY : Sources/DataBase/KD/Container.s

# target to generate assembly for a file
Sources/DataBase/KD/Container.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/Container.cpp.s
.PHONY : Sources/DataBase/KD/Container.cpp.s

Sources/DataBase/KD/DB.o: Sources/DataBase/KD/DB.cpp.o

.PHONY : Sources/DataBase/KD/DB.o

# target to build an object file
Sources/DataBase/KD/DB.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DB.cpp.o
.PHONY : Sources/DataBase/KD/DB.cpp.o

Sources/DataBase/KD/DB.i: Sources/DataBase/KD/DB.cpp.i

.PHONY : Sources/DataBase/KD/DB.i

# target to preprocess a source file
Sources/DataBase/KD/DB.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DB.cpp.i
.PHONY : Sources/DataBase/KD/DB.cpp.i

Sources/DataBase/KD/DB.s: Sources/DataBase/KD/DB.cpp.s

.PHONY : Sources/DataBase/KD/DB.s

# target to generate assembly for a file
Sources/DataBase/KD/DB.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DB.cpp.s
.PHONY : Sources/DataBase/KD/DB.cpp.s

Sources/DataBase/KD/DBManager.o: Sources/DataBase/KD/DBManager.cpp.o

.PHONY : Sources/DataBase/KD/DBManager.o

# target to build an object file
Sources/DataBase/KD/DBManager.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DBManager.cpp.o
.PHONY : Sources/DataBase/KD/DBManager.cpp.o

Sources/DataBase/KD/DBManager.i: Sources/DataBase/KD/DBManager.cpp.i

.PHONY : Sources/DataBase/KD/DBManager.i

# target to preprocess a source file
Sources/DataBase/KD/DBManager.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DBManager.cpp.i
.PHONY : Sources/DataBase/KD/DBManager.cpp.i

Sources/DataBase/KD/DBManager.s: Sources/DataBase/KD/DBManager.cpp.s

.PHONY : Sources/DataBase/KD/DBManager.s

# target to generate assembly for a file
Sources/DataBase/KD/DBManager.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/DBManager.cpp.s
.PHONY : Sources/DataBase/KD/DBManager.cpp.s

Sources/DataBase/KD/KDTree.o: Sources/DataBase/KD/KDTree.cpp.o

.PHONY : Sources/DataBase/KD/KDTree.o

# target to build an object file
Sources/DataBase/KD/KDTree.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/KDTree.cpp.o
.PHONY : Sources/DataBase/KD/KDTree.cpp.o

Sources/DataBase/KD/KDTree.i: Sources/DataBase/KD/KDTree.cpp.i

.PHONY : Sources/DataBase/KD/KDTree.i

# target to preprocess a source file
Sources/DataBase/KD/KDTree.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/KDTree.cpp.i
.PHONY : Sources/DataBase/KD/KDTree.cpp.i

Sources/DataBase/KD/KDTree.s: Sources/DataBase/KD/KDTree.cpp.s

.PHONY : Sources/DataBase/KD/KDTree.s

# target to generate assembly for a file
Sources/DataBase/KD/KDTree.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/KDTree.cpp.s
.PHONY : Sources/DataBase/KD/KDTree.cpp.s

Sources/DataBase/KD/SearchEngine.o: Sources/DataBase/KD/SearchEngine.cpp.o

.PHONY : Sources/DataBase/KD/SearchEngine.o

# target to build an object file
Sources/DataBase/KD/SearchEngine.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/SearchEngine.cpp.o
.PHONY : Sources/DataBase/KD/SearchEngine.cpp.o

Sources/DataBase/KD/SearchEngine.i: Sources/DataBase/KD/SearchEngine.cpp.i

.PHONY : Sources/DataBase/KD/SearchEngine.i

# target to preprocess a source file
Sources/DataBase/KD/SearchEngine.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/SearchEngine.cpp.i
.PHONY : Sources/DataBase/KD/SearchEngine.cpp.i

Sources/DataBase/KD/SearchEngine.s: Sources/DataBase/KD/SearchEngine.cpp.s

.PHONY : Sources/DataBase/KD/SearchEngine.s

# target to generate assembly for a file
Sources/DataBase/KD/SearchEngine.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/DataBase/KD/SearchEngine.cpp.s
.PHONY : Sources/DataBase/KD/SearchEngine.cpp.s

Sources/StaticGeneration/APIJsonSeializator/Serializator.o: Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.o

.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.o

# target to build an object file
Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.o
.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.o

Sources/StaticGeneration/APIJsonSeializator/Serializator.i: Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.i

.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.i

# target to preprocess a source file
Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.i
.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.i

Sources/StaticGeneration/APIJsonSeializator/Serializator.s: Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.s

.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.s

# target to generate assembly for a file
Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.s
.PHONY : Sources/StaticGeneration/APIJsonSeializator/Serializator.cpp.s

Sources/StaticGeneration/Page/Page.o: Sources/StaticGeneration/Page/Page.cpp.o

.PHONY : Sources/StaticGeneration/Page/Page.o

# target to build an object file
Sources/StaticGeneration/Page/Page.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Page/Page.cpp.o
.PHONY : Sources/StaticGeneration/Page/Page.cpp.o

Sources/StaticGeneration/Page/Page.i: Sources/StaticGeneration/Page/Page.cpp.i

.PHONY : Sources/StaticGeneration/Page/Page.i

# target to preprocess a source file
Sources/StaticGeneration/Page/Page.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Page/Page.cpp.i
.PHONY : Sources/StaticGeneration/Page/Page.cpp.i

Sources/StaticGeneration/Page/Page.s: Sources/StaticGeneration/Page/Page.cpp.s

.PHONY : Sources/StaticGeneration/Page/Page.s

# target to generate assembly for a file
Sources/StaticGeneration/Page/Page.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Page/Page.cpp.s
.PHONY : Sources/StaticGeneration/Page/Page.cpp.s

Sources/StaticGeneration/PageData/PageData.o: Sources/StaticGeneration/PageData/PageData.cpp.o

.PHONY : Sources/StaticGeneration/PageData/PageData.o

# target to build an object file
Sources/StaticGeneration/PageData/PageData.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageData/PageData.cpp.o
.PHONY : Sources/StaticGeneration/PageData/PageData.cpp.o

Sources/StaticGeneration/PageData/PageData.i: Sources/StaticGeneration/PageData/PageData.cpp.i

.PHONY : Sources/StaticGeneration/PageData/PageData.i

# target to preprocess a source file
Sources/StaticGeneration/PageData/PageData.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageData/PageData.cpp.i
.PHONY : Sources/StaticGeneration/PageData/PageData.cpp.i

Sources/StaticGeneration/PageData/PageData.s: Sources/StaticGeneration/PageData/PageData.cpp.s

.PHONY : Sources/StaticGeneration/PageData/PageData.s

# target to generate assembly for a file
Sources/StaticGeneration/PageData/PageData.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageData/PageData.cpp.s
.PHONY : Sources/StaticGeneration/PageData/PageData.cpp.s

Sources/StaticGeneration/PageGenerator/PageGenerator.o: Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.o

.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.o

# target to build an object file
Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.o
.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.o

Sources/StaticGeneration/PageGenerator/PageGenerator.i: Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.i

.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.i

# target to preprocess a source file
Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.i
.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.i

Sources/StaticGeneration/PageGenerator/PageGenerator.s: Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.s

.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.s

# target to generate assembly for a file
Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.s
.PHONY : Sources/StaticGeneration/PageGenerator/PageGenerator.cpp.s

Sources/StaticGeneration/PageManager/PageManager.o: Sources/StaticGeneration/PageManager/PageManager.cpp.o

.PHONY : Sources/StaticGeneration/PageManager/PageManager.o

# target to build an object file
Sources/StaticGeneration/PageManager/PageManager.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageManager/PageManager.cpp.o
.PHONY : Sources/StaticGeneration/PageManager/PageManager.cpp.o

Sources/StaticGeneration/PageManager/PageManager.i: Sources/StaticGeneration/PageManager/PageManager.cpp.i

.PHONY : Sources/StaticGeneration/PageManager/PageManager.i

# target to preprocess a source file
Sources/StaticGeneration/PageManager/PageManager.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageManager/PageManager.cpp.i
.PHONY : Sources/StaticGeneration/PageManager/PageManager.cpp.i

Sources/StaticGeneration/PageManager/PageManager.s: Sources/StaticGeneration/PageManager/PageManager.cpp.s

.PHONY : Sources/StaticGeneration/PageManager/PageManager.s

# target to generate assembly for a file
Sources/StaticGeneration/PageManager/PageManager.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/PageManager/PageManager.cpp.s
.PHONY : Sources/StaticGeneration/PageManager/PageManager.cpp.s

Sources/StaticGeneration/Views/Cell/CellView.o: Sources/StaticGeneration/Views/Cell/CellView.cpp.o

.PHONY : Sources/StaticGeneration/Views/Cell/CellView.o

# target to build an object file
Sources/StaticGeneration/Views/Cell/CellView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Cell/CellView.cpp.o
.PHONY : Sources/StaticGeneration/Views/Cell/CellView.cpp.o

Sources/StaticGeneration/Views/Cell/CellView.i: Sources/StaticGeneration/Views/Cell/CellView.cpp.i

.PHONY : Sources/StaticGeneration/Views/Cell/CellView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/Cell/CellView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Cell/CellView.cpp.i
.PHONY : Sources/StaticGeneration/Views/Cell/CellView.cpp.i

Sources/StaticGeneration/Views/Cell/CellView.s: Sources/StaticGeneration/Views/Cell/CellView.cpp.s

.PHONY : Sources/StaticGeneration/Views/Cell/CellView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/Cell/CellView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Cell/CellView.cpp.s
.PHONY : Sources/StaticGeneration/Views/Cell/CellView.cpp.s

Sources/StaticGeneration/Views/Container/ContainerView.o: Sources/StaticGeneration/Views/Container/ContainerView.cpp.o

.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.o

# target to build an object file
Sources/StaticGeneration/Views/Container/ContainerView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Container/ContainerView.cpp.o
.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.cpp.o

Sources/StaticGeneration/Views/Container/ContainerView.i: Sources/StaticGeneration/Views/Container/ContainerView.cpp.i

.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/Container/ContainerView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Container/ContainerView.cpp.i
.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.cpp.i

Sources/StaticGeneration/Views/Container/ContainerView.s: Sources/StaticGeneration/Views/Container/ContainerView.cpp.s

.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/Container/ContainerView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Container/ContainerView.cpp.s
.PHONY : Sources/StaticGeneration/Views/Container/ContainerView.cpp.s

Sources/StaticGeneration/Views/Form/FormView.o: Sources/StaticGeneration/Views/Form/FormView.cpp.o

.PHONY : Sources/StaticGeneration/Views/Form/FormView.o

# target to build an object file
Sources/StaticGeneration/Views/Form/FormView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Form/FormView.cpp.o
.PHONY : Sources/StaticGeneration/Views/Form/FormView.cpp.o

Sources/StaticGeneration/Views/Form/FormView.i: Sources/StaticGeneration/Views/Form/FormView.cpp.i

.PHONY : Sources/StaticGeneration/Views/Form/FormView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/Form/FormView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Form/FormView.cpp.i
.PHONY : Sources/StaticGeneration/Views/Form/FormView.cpp.i

Sources/StaticGeneration/Views/Form/FormView.s: Sources/StaticGeneration/Views/Form/FormView.cpp.s

.PHONY : Sources/StaticGeneration/Views/Form/FormView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/Form/FormView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Form/FormView.cpp.s
.PHONY : Sources/StaticGeneration/Views/Form/FormView.cpp.s

Sources/StaticGeneration/Views/ImageView/ImageView.o: Sources/StaticGeneration/Views/ImageView/ImageView.cpp.o

.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.o

# target to build an object file
Sources/StaticGeneration/Views/ImageView/ImageView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/ImageView/ImageView.cpp.o
.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.cpp.o

Sources/StaticGeneration/Views/ImageView/ImageView.i: Sources/StaticGeneration/Views/ImageView/ImageView.cpp.i

.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/ImageView/ImageView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/ImageView/ImageView.cpp.i
.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.cpp.i

Sources/StaticGeneration/Views/ImageView/ImageView.s: Sources/StaticGeneration/Views/ImageView/ImageView.cpp.s

.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/ImageView/ImageView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/ImageView/ImageView.cpp.s
.PHONY : Sources/StaticGeneration/Views/ImageView/ImageView.cpp.s

Sources/StaticGeneration/Views/PersonView/PersonView.o: Sources/StaticGeneration/Views/PersonView/PersonView.cpp.o

.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.o

# target to build an object file
Sources/StaticGeneration/Views/PersonView/PersonView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/PersonView/PersonView.cpp.o
.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.cpp.o

Sources/StaticGeneration/Views/PersonView/PersonView.i: Sources/StaticGeneration/Views/PersonView/PersonView.cpp.i

.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/PersonView/PersonView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/PersonView/PersonView.cpp.i
.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.cpp.i

Sources/StaticGeneration/Views/PersonView/PersonView.s: Sources/StaticGeneration/Views/PersonView/PersonView.cpp.s

.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/PersonView/PersonView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/PersonView/PersonView.cpp.s
.PHONY : Sources/StaticGeneration/Views/PersonView/PersonView.cpp.s

Sources/StaticGeneration/Views/Row/RowView.o: Sources/StaticGeneration/Views/Row/RowView.cpp.o

.PHONY : Sources/StaticGeneration/Views/Row/RowView.o

# target to build an object file
Sources/StaticGeneration/Views/Row/RowView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Row/RowView.cpp.o
.PHONY : Sources/StaticGeneration/Views/Row/RowView.cpp.o

Sources/StaticGeneration/Views/Row/RowView.i: Sources/StaticGeneration/Views/Row/RowView.cpp.i

.PHONY : Sources/StaticGeneration/Views/Row/RowView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/Row/RowView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Row/RowView.cpp.i
.PHONY : Sources/StaticGeneration/Views/Row/RowView.cpp.i

Sources/StaticGeneration/Views/Row/RowView.s: Sources/StaticGeneration/Views/Row/RowView.cpp.s

.PHONY : Sources/StaticGeneration/Views/Row/RowView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/Row/RowView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/Row/RowView.cpp.s
.PHONY : Sources/StaticGeneration/Views/Row/RowView.cpp.s

Sources/StaticGeneration/Views/SecondaryView/SecondaryView.o: Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.o

.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.o

# target to build an object file
Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.o
.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.o

Sources/StaticGeneration/Views/SecondaryView/SecondaryView.i: Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.i

.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.i
.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.i

Sources/StaticGeneration/Views/SecondaryView/SecondaryView.s: Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.s

.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.s
.PHONY : Sources/StaticGeneration/Views/SecondaryView/SecondaryView.cpp.s

Sources/StaticGeneration/Views/TableView/TableView.o: Sources/StaticGeneration/Views/TableView/TableView.cpp.o

.PHONY : Sources/StaticGeneration/Views/TableView/TableView.o

# target to build an object file
Sources/StaticGeneration/Views/TableView/TableView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TableView/TableView.cpp.o
.PHONY : Sources/StaticGeneration/Views/TableView/TableView.cpp.o

Sources/StaticGeneration/Views/TableView/TableView.i: Sources/StaticGeneration/Views/TableView/TableView.cpp.i

.PHONY : Sources/StaticGeneration/Views/TableView/TableView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/TableView/TableView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TableView/TableView.cpp.i
.PHONY : Sources/StaticGeneration/Views/TableView/TableView.cpp.i

Sources/StaticGeneration/Views/TableView/TableView.s: Sources/StaticGeneration/Views/TableView/TableView.cpp.s

.PHONY : Sources/StaticGeneration/Views/TableView/TableView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/TableView/TableView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TableView/TableView.cpp.s
.PHONY : Sources/StaticGeneration/Views/TableView/TableView.cpp.s

Sources/StaticGeneration/Views/TextView/TextView.o: Sources/StaticGeneration/Views/TextView/TextView.cpp.o

.PHONY : Sources/StaticGeneration/Views/TextView/TextView.o

# target to build an object file
Sources/StaticGeneration/Views/TextView/TextView.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TextView/TextView.cpp.o
.PHONY : Sources/StaticGeneration/Views/TextView/TextView.cpp.o

Sources/StaticGeneration/Views/TextView/TextView.i: Sources/StaticGeneration/Views/TextView/TextView.cpp.i

.PHONY : Sources/StaticGeneration/Views/TextView/TextView.i

# target to preprocess a source file
Sources/StaticGeneration/Views/TextView/TextView.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TextView/TextView.cpp.i
.PHONY : Sources/StaticGeneration/Views/TextView/TextView.cpp.i

Sources/StaticGeneration/Views/TextView/TextView.s: Sources/StaticGeneration/Views/TextView/TextView.cpp.s

.PHONY : Sources/StaticGeneration/Views/TextView/TextView.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/TextView/TextView.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/TextView/TextView.cpp.s
.PHONY : Sources/StaticGeneration/Views/TextView/TextView.cpp.s

Sources/StaticGeneration/Views/UserData/UserData.o: Sources/StaticGeneration/Views/UserData/UserData.cpp.o

.PHONY : Sources/StaticGeneration/Views/UserData/UserData.o

# target to build an object file
Sources/StaticGeneration/Views/UserData/UserData.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/UserData/UserData.cpp.o
.PHONY : Sources/StaticGeneration/Views/UserData/UserData.cpp.o

Sources/StaticGeneration/Views/UserData/UserData.i: Sources/StaticGeneration/Views/UserData/UserData.cpp.i

.PHONY : Sources/StaticGeneration/Views/UserData/UserData.i

# target to preprocess a source file
Sources/StaticGeneration/Views/UserData/UserData.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/UserData/UserData.cpp.i
.PHONY : Sources/StaticGeneration/Views/UserData/UserData.cpp.i

Sources/StaticGeneration/Views/UserData/UserData.s: Sources/StaticGeneration/Views/UserData/UserData.cpp.s

.PHONY : Sources/StaticGeneration/Views/UserData/UserData.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/UserData/UserData.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/UserData/UserData.cpp.s
.PHONY : Sources/StaticGeneration/Views/UserData/UserData.cpp.s

Sources/StaticGeneration/Views/View/View.o: Sources/StaticGeneration/Views/View/View.cpp.o

.PHONY : Sources/StaticGeneration/Views/View/View.o

# target to build an object file
Sources/StaticGeneration/Views/View/View.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/View/View.cpp.o
.PHONY : Sources/StaticGeneration/Views/View/View.cpp.o

Sources/StaticGeneration/Views/View/View.i: Sources/StaticGeneration/Views/View/View.cpp.i

.PHONY : Sources/StaticGeneration/Views/View/View.i

# target to preprocess a source file
Sources/StaticGeneration/Views/View/View.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/View/View.cpp.i
.PHONY : Sources/StaticGeneration/Views/View/View.cpp.i

Sources/StaticGeneration/Views/View/View.s: Sources/StaticGeneration/Views/View/View.cpp.s

.PHONY : Sources/StaticGeneration/Views/View/View.s

# target to generate assembly for a file
Sources/StaticGeneration/Views/View/View.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/StaticGeneration/Views/View/View.cpp.s
.PHONY : Sources/StaticGeneration/Views/View/View.cpp.s

Sources/WebCrowler/API/FacebookAPI.o: Sources/WebCrowler/API/FacebookAPI.cpp.o

.PHONY : Sources/WebCrowler/API/FacebookAPI.o

# target to build an object file
Sources/WebCrowler/API/FacebookAPI.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/FacebookAPI.cpp.o
.PHONY : Sources/WebCrowler/API/FacebookAPI.cpp.o

Sources/WebCrowler/API/FacebookAPI.i: Sources/WebCrowler/API/FacebookAPI.cpp.i

.PHONY : Sources/WebCrowler/API/FacebookAPI.i

# target to preprocess a source file
Sources/WebCrowler/API/FacebookAPI.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/FacebookAPI.cpp.i
.PHONY : Sources/WebCrowler/API/FacebookAPI.cpp.i

Sources/WebCrowler/API/FacebookAPI.s: Sources/WebCrowler/API/FacebookAPI.cpp.s

.PHONY : Sources/WebCrowler/API/FacebookAPI.s

# target to generate assembly for a file
Sources/WebCrowler/API/FacebookAPI.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/FacebookAPI.cpp.s
.PHONY : Sources/WebCrowler/API/FacebookAPI.cpp.s

Sources/WebCrowler/API/OkAPI.o: Sources/WebCrowler/API/OkAPI.cpp.o

.PHONY : Sources/WebCrowler/API/OkAPI.o

# target to build an object file
Sources/WebCrowler/API/OkAPI.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/OkAPI.cpp.o
.PHONY : Sources/WebCrowler/API/OkAPI.cpp.o

Sources/WebCrowler/API/OkAPI.i: Sources/WebCrowler/API/OkAPI.cpp.i

.PHONY : Sources/WebCrowler/API/OkAPI.i

# target to preprocess a source file
Sources/WebCrowler/API/OkAPI.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/OkAPI.cpp.i
.PHONY : Sources/WebCrowler/API/OkAPI.cpp.i

Sources/WebCrowler/API/OkAPI.s: Sources/WebCrowler/API/OkAPI.cpp.s

.PHONY : Sources/WebCrowler/API/OkAPI.s

# target to generate assembly for a file
Sources/WebCrowler/API/OkAPI.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/OkAPI.cpp.s
.PHONY : Sources/WebCrowler/API/OkAPI.cpp.s

Sources/WebCrowler/API/VkAPI.o: Sources/WebCrowler/API/VkAPI.cpp.o

.PHONY : Sources/WebCrowler/API/VkAPI.o

# target to build an object file
Sources/WebCrowler/API/VkAPI.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/VkAPI.cpp.o
.PHONY : Sources/WebCrowler/API/VkAPI.cpp.o

Sources/WebCrowler/API/VkAPI.i: Sources/WebCrowler/API/VkAPI.cpp.i

.PHONY : Sources/WebCrowler/API/VkAPI.i

# target to preprocess a source file
Sources/WebCrowler/API/VkAPI.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/VkAPI.cpp.i
.PHONY : Sources/WebCrowler/API/VkAPI.cpp.i

Sources/WebCrowler/API/VkAPI.s: Sources/WebCrowler/API/VkAPI.cpp.s

.PHONY : Sources/WebCrowler/API/VkAPI.s

# target to generate assembly for a file
Sources/WebCrowler/API/VkAPI.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/API/VkAPI.cpp.s
.PHONY : Sources/WebCrowler/API/VkAPI.cpp.s

Sources/WebCrowler/Crowler/Crowler.o: Sources/WebCrowler/Crowler/Crowler.cpp.o

.PHONY : Sources/WebCrowler/Crowler/Crowler.o

# target to build an object file
Sources/WebCrowler/Crowler/Crowler.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Crowler/Crowler.cpp.o
.PHONY : Sources/WebCrowler/Crowler/Crowler.cpp.o

Sources/WebCrowler/Crowler/Crowler.i: Sources/WebCrowler/Crowler/Crowler.cpp.i

.PHONY : Sources/WebCrowler/Crowler/Crowler.i

# target to preprocess a source file
Sources/WebCrowler/Crowler/Crowler.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Crowler/Crowler.cpp.i
.PHONY : Sources/WebCrowler/Crowler/Crowler.cpp.i

Sources/WebCrowler/Crowler/Crowler.s: Sources/WebCrowler/Crowler/Crowler.cpp.s

.PHONY : Sources/WebCrowler/Crowler/Crowler.s

# target to generate assembly for a file
Sources/WebCrowler/Crowler/Crowler.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Crowler/Crowler.cpp.s
.PHONY : Sources/WebCrowler/Crowler/Crowler.cpp.s

Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.o: Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.o

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.o

# target to build an object file
Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.o
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.o

Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.i: Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.i

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.i

# target to preprocess a source file
Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.i
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.i

Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.s: Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.s

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.s

# target to generate assembly for a file
Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.s
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.cpp.s

Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.o: Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.o

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.o

# target to build an object file
Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.o
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.o

Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.i: Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.i

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.i

# target to preprocess a source file
Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.i
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.i

Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.s: Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.s

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.s

# target to generate assembly for a file
Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.s
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.cpp.s

Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.o: Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.o

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.o

# target to build an object file
Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.o
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.o

Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.i: Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.i

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.i

# target to preprocess a source file
Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.i
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.i

Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.s: Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.s

.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.s

# target to generate assembly for a file
Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.s
.PHONY : Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.cpp.s

Sources/WebCrowler/NetService/NetService.o: Sources/WebCrowler/NetService/NetService.cpp.o

.PHONY : Sources/WebCrowler/NetService/NetService.o

# target to build an object file
Sources/WebCrowler/NetService/NetService.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/NetService/NetService.cpp.o
.PHONY : Sources/WebCrowler/NetService/NetService.cpp.o

Sources/WebCrowler/NetService/NetService.i: Sources/WebCrowler/NetService/NetService.cpp.i

.PHONY : Sources/WebCrowler/NetService/NetService.i

# target to preprocess a source file
Sources/WebCrowler/NetService/NetService.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/NetService/NetService.cpp.i
.PHONY : Sources/WebCrowler/NetService/NetService.cpp.i

Sources/WebCrowler/NetService/NetService.s: Sources/WebCrowler/NetService/NetService.cpp.s

.PHONY : Sources/WebCrowler/NetService/NetService.s

# target to generate assembly for a file
Sources/WebCrowler/NetService/NetService.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/NetService/NetService.cpp.s
.PHONY : Sources/WebCrowler/NetService/NetService.cpp.s

Sources/WebCrowler/response/response.o: Sources/WebCrowler/response/response.cpp.o

.PHONY : Sources/WebCrowler/response/response.o

# target to build an object file
Sources/WebCrowler/response/response.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/response/response.cpp.o
.PHONY : Sources/WebCrowler/response/response.cpp.o

Sources/WebCrowler/response/response.i: Sources/WebCrowler/response/response.cpp.i

.PHONY : Sources/WebCrowler/response/response.i

# target to preprocess a source file
Sources/WebCrowler/response/response.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/response/response.cpp.i
.PHONY : Sources/WebCrowler/response/response.cpp.i

Sources/WebCrowler/response/response.s: Sources/WebCrowler/response/response.cpp.s

.PHONY : Sources/WebCrowler/response/response.s

# target to generate assembly for a file
Sources/WebCrowler/response/response.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebCrowler/response/response.cpp.s
.PHONY : Sources/WebCrowler/response/response.cpp.s

Sources/WebServer/HttpRequest/HttpRequest.o: Sources/WebServer/HttpRequest/HttpRequest.cpp.o

.PHONY : Sources/WebServer/HttpRequest/HttpRequest.o

# target to build an object file
Sources/WebServer/HttpRequest/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpRequest/HttpRequest.cpp.o
.PHONY : Sources/WebServer/HttpRequest/HttpRequest.cpp.o

Sources/WebServer/HttpRequest/HttpRequest.i: Sources/WebServer/HttpRequest/HttpRequest.cpp.i

.PHONY : Sources/WebServer/HttpRequest/HttpRequest.i

# target to preprocess a source file
Sources/WebServer/HttpRequest/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpRequest/HttpRequest.cpp.i
.PHONY : Sources/WebServer/HttpRequest/HttpRequest.cpp.i

Sources/WebServer/HttpRequest/HttpRequest.s: Sources/WebServer/HttpRequest/HttpRequest.cpp.s

.PHONY : Sources/WebServer/HttpRequest/HttpRequest.s

# target to generate assembly for a file
Sources/WebServer/HttpRequest/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpRequest/HttpRequest.cpp.s
.PHONY : Sources/WebServer/HttpRequest/HttpRequest.cpp.s

Sources/WebServer/HttpResponse/HttpResponse.o: Sources/WebServer/HttpResponse/HttpResponse.cpp.o

.PHONY : Sources/WebServer/HttpResponse/HttpResponse.o

# target to build an object file
Sources/WebServer/HttpResponse/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpResponse/HttpResponse.cpp.o
.PHONY : Sources/WebServer/HttpResponse/HttpResponse.cpp.o

Sources/WebServer/HttpResponse/HttpResponse.i: Sources/WebServer/HttpResponse/HttpResponse.cpp.i

.PHONY : Sources/WebServer/HttpResponse/HttpResponse.i

# target to preprocess a source file
Sources/WebServer/HttpResponse/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpResponse/HttpResponse.cpp.i
.PHONY : Sources/WebServer/HttpResponse/HttpResponse.cpp.i

Sources/WebServer/HttpResponse/HttpResponse.s: Sources/WebServer/HttpResponse/HttpResponse.cpp.s

.PHONY : Sources/WebServer/HttpResponse/HttpResponse.s

# target to generate assembly for a file
Sources/WebServer/HttpResponse/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/HttpResponse/HttpResponse.cpp.s
.PHONY : Sources/WebServer/HttpResponse/HttpResponse.cpp.s

Sources/WebServer/LRU/LRU.o: Sources/WebServer/LRU/LRU.cpp.o

.PHONY : Sources/WebServer/LRU/LRU.o

# target to build an object file
Sources/WebServer/LRU/LRU.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/LRU/LRU.cpp.o
.PHONY : Sources/WebServer/LRU/LRU.cpp.o

Sources/WebServer/LRU/LRU.i: Sources/WebServer/LRU/LRU.cpp.i

.PHONY : Sources/WebServer/LRU/LRU.i

# target to preprocess a source file
Sources/WebServer/LRU/LRU.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/LRU/LRU.cpp.i
.PHONY : Sources/WebServer/LRU/LRU.cpp.i

Sources/WebServer/LRU/LRU.s: Sources/WebServer/LRU/LRU.cpp.s

.PHONY : Sources/WebServer/LRU/LRU.s

# target to generate assembly for a file
Sources/WebServer/LRU/LRU.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/LRU/LRU.cpp.s
.PHONY : Sources/WebServer/LRU/LRU.cpp.s

Sources/WebServer/Server/Server.o: Sources/WebServer/Server/Server.cpp.o

.PHONY : Sources/WebServer/Server/Server.o

# target to build an object file
Sources/WebServer/Server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/Server/Server.cpp.o
.PHONY : Sources/WebServer/Server/Server.cpp.o

Sources/WebServer/Server/Server.i: Sources/WebServer/Server/Server.cpp.i

.PHONY : Sources/WebServer/Server/Server.i

# target to preprocess a source file
Sources/WebServer/Server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/Server/Server.cpp.i
.PHONY : Sources/WebServer/Server/Server.cpp.i

Sources/WebServer/Server/Server.s: Sources/WebServer/Server/Server.cpp.s

.PHONY : Sources/WebServer/Server/Server.s

# target to generate assembly for a file
Sources/WebServer/Server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/WebServer/Server/Server.cpp.s
.PHONY : Sources/WebServer/Server/Server.cpp.s

Sources/main.o: Sources/main.cpp.o

.PHONY : Sources/main.o

# target to build an object file
Sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/main.cpp.o
.PHONY : Sources/main.cpp.o

Sources/main.i: Sources/main.cpp.i

.PHONY : Sources/main.i

# target to preprocess a source file
Sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/main.cpp.i
.PHONY : Sources/main.cpp.i

Sources/main.s: Sources/main.cpp.s

.PHONY : Sources/main.s

# target to generate assembly for a file
Sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/CPProject.out.dir/build.make CMakeFiles/CPProject.out.dir/Sources/main.cpp.s
.PHONY : Sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... CPProject.out"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Google_Tests_run"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Sources/DataBase/Base/BaseComporator.o"
	@echo "... Sources/DataBase/Base/BaseComporator.i"
	@echo "... Sources/DataBase/Base/BaseComporator.s"
	@echo "... Sources/DataBase/Base/BaseContainer.o"
	@echo "... Sources/DataBase/Base/BaseContainer.i"
	@echo "... Sources/DataBase/Base/BaseContainer.s"
	@echo "... Sources/DataBase/Base/BaseDataStructure.o"
	@echo "... Sources/DataBase/Base/BaseDataStructure.i"
	@echo "... Sources/DataBase/Base/BaseDataStructure.s"
	@echo "... Sources/DataBase/Base/BaseMetrificator.o"
	@echo "... Sources/DataBase/Base/BaseMetrificator.i"
	@echo "... Sources/DataBase/Base/BaseMetrificator.s"
	@echo "... Sources/DataBase/Base/BaseSearchEngine.o"
	@echo "... Sources/DataBase/Base/BaseSearchEngine.i"
	@echo "... Sources/DataBase/Base/BaseSearchEngine.s"
	@echo "... Sources/DataBase/KD/Container.o"
	@echo "... Sources/DataBase/KD/Container.i"
	@echo "... Sources/DataBase/KD/Container.s"
	@echo "... Sources/DataBase/KD/DB.o"
	@echo "... Sources/DataBase/KD/DB.i"
	@echo "... Sources/DataBase/KD/DB.s"
	@echo "... Sources/DataBase/KD/DBManager.o"
	@echo "... Sources/DataBase/KD/DBManager.i"
	@echo "... Sources/DataBase/KD/DBManager.s"
	@echo "... Sources/DataBase/KD/KDTree.o"
	@echo "... Sources/DataBase/KD/KDTree.i"
	@echo "... Sources/DataBase/KD/KDTree.s"
	@echo "... Sources/DataBase/KD/SearchEngine.o"
	@echo "... Sources/DataBase/KD/SearchEngine.i"
	@echo "... Sources/DataBase/KD/SearchEngine.s"
	@echo "... Sources/StaticGeneration/APIJsonSeializator/Serializator.o"
	@echo "... Sources/StaticGeneration/APIJsonSeializator/Serializator.i"
	@echo "... Sources/StaticGeneration/APIJsonSeializator/Serializator.s"
	@echo "... Sources/StaticGeneration/Page/Page.o"
	@echo "... Sources/StaticGeneration/Page/Page.i"
	@echo "... Sources/StaticGeneration/Page/Page.s"
	@echo "... Sources/StaticGeneration/PageData/PageData.o"
	@echo "... Sources/StaticGeneration/PageData/PageData.i"
	@echo "... Sources/StaticGeneration/PageData/PageData.s"
	@echo "... Sources/StaticGeneration/PageGenerator/PageGenerator.o"
	@echo "... Sources/StaticGeneration/PageGenerator/PageGenerator.i"
	@echo "... Sources/StaticGeneration/PageGenerator/PageGenerator.s"
	@echo "... Sources/StaticGeneration/PageManager/PageManager.o"
	@echo "... Sources/StaticGeneration/PageManager/PageManager.i"
	@echo "... Sources/StaticGeneration/PageManager/PageManager.s"
	@echo "... Sources/StaticGeneration/Views/Cell/CellView.o"
	@echo "... Sources/StaticGeneration/Views/Cell/CellView.i"
	@echo "... Sources/StaticGeneration/Views/Cell/CellView.s"
	@echo "... Sources/StaticGeneration/Views/Container/ContainerView.o"
	@echo "... Sources/StaticGeneration/Views/Container/ContainerView.i"
	@echo "... Sources/StaticGeneration/Views/Container/ContainerView.s"
	@echo "... Sources/StaticGeneration/Views/Form/FormView.o"
	@echo "... Sources/StaticGeneration/Views/Form/FormView.i"
	@echo "... Sources/StaticGeneration/Views/Form/FormView.s"
	@echo "... Sources/StaticGeneration/Views/ImageView/ImageView.o"
	@echo "... Sources/StaticGeneration/Views/ImageView/ImageView.i"
	@echo "... Sources/StaticGeneration/Views/ImageView/ImageView.s"
	@echo "... Sources/StaticGeneration/Views/PersonView/PersonView.o"
	@echo "... Sources/StaticGeneration/Views/PersonView/PersonView.i"
	@echo "... Sources/StaticGeneration/Views/PersonView/PersonView.s"
	@echo "... Sources/StaticGeneration/Views/Row/RowView.o"
	@echo "... Sources/StaticGeneration/Views/Row/RowView.i"
	@echo "... Sources/StaticGeneration/Views/Row/RowView.s"
	@echo "... Sources/StaticGeneration/Views/SecondaryView/SecondaryView.o"
	@echo "... Sources/StaticGeneration/Views/SecondaryView/SecondaryView.i"
	@echo "... Sources/StaticGeneration/Views/SecondaryView/SecondaryView.s"
	@echo "... Sources/StaticGeneration/Views/TableView/TableView.o"
	@echo "... Sources/StaticGeneration/Views/TableView/TableView.i"
	@echo "... Sources/StaticGeneration/Views/TableView/TableView.s"
	@echo "... Sources/StaticGeneration/Views/TextView/TextView.o"
	@echo "... Sources/StaticGeneration/Views/TextView/TextView.i"
	@echo "... Sources/StaticGeneration/Views/TextView/TextView.s"
	@echo "... Sources/StaticGeneration/Views/UserData/UserData.o"
	@echo "... Sources/StaticGeneration/Views/UserData/UserData.i"
	@echo "... Sources/StaticGeneration/Views/UserData/UserData.s"
	@echo "... Sources/StaticGeneration/Views/View/View.o"
	@echo "... Sources/StaticGeneration/Views/View/View.i"
	@echo "... Sources/StaticGeneration/Views/View/View.s"
	@echo "... Sources/WebCrowler/API/FacebookAPI.o"
	@echo "... Sources/WebCrowler/API/FacebookAPI.i"
	@echo "... Sources/WebCrowler/API/FacebookAPI.s"
	@echo "... Sources/WebCrowler/API/OkAPI.o"
	@echo "... Sources/WebCrowler/API/OkAPI.i"
	@echo "... Sources/WebCrowler/API/OkAPI.s"
	@echo "... Sources/WebCrowler/API/VkAPI.o"
	@echo "... Sources/WebCrowler/API/VkAPI.i"
	@echo "... Sources/WebCrowler/API/VkAPI.s"
	@echo "... Sources/WebCrowler/Crowler/Crowler.o"
	@echo "... Sources/WebCrowler/Crowler/Crowler.i"
	@echo "... Sources/WebCrowler/Crowler/Crowler.s"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.o"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.i"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Facebook_id_list_generator_strategy.s"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.o"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.i"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Ok_id_list_generator_strategy.s"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.o"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.i"
	@echo "... Sources/WebCrowler/Id_list_generator_strategy/Vk_id_list_generator_strategy.s"
	@echo "... Sources/WebCrowler/NetService/NetService.o"
	@echo "... Sources/WebCrowler/NetService/NetService.i"
	@echo "... Sources/WebCrowler/NetService/NetService.s"
	@echo "... Sources/WebCrowler/response/response.o"
	@echo "... Sources/WebCrowler/response/response.i"
	@echo "... Sources/WebCrowler/response/response.s"
	@echo "... Sources/WebServer/HttpRequest/HttpRequest.o"
	@echo "... Sources/WebServer/HttpRequest/HttpRequest.i"
	@echo "... Sources/WebServer/HttpRequest/HttpRequest.s"
	@echo "... Sources/WebServer/HttpResponse/HttpResponse.o"
	@echo "... Sources/WebServer/HttpResponse/HttpResponse.i"
	@echo "... Sources/WebServer/HttpResponse/HttpResponse.s"
	@echo "... Sources/WebServer/LRU/LRU.o"
	@echo "... Sources/WebServer/LRU/LRU.i"
	@echo "... Sources/WebServer/LRU/LRU.s"
	@echo "... Sources/WebServer/Server/Server.o"
	@echo "... Sources/WebServer/Server/Server.i"
	@echo "... Sources/WebServer/Server/Server.s"
	@echo "... Sources/main.o"
	@echo "... Sources/main.i"
	@echo "... Sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

